const maps = [
      [
      "fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
      "m      H  mm                                                                                                 m",
      "m   u  H  mm                                                                                                   m",
      "m      H  mm                                                                                                     m",
      "m      H  mm                                                                                                   m",
      "mq l   H  mm                                                                                              mm",
      "mffffffH  mm                                                                                          $-   mm",
      "m      H                                                                                             $-     m",
      "m      H                                                                                                $- m",
      "m      H  mm                                                                                               m",
      "m      H  mm                                                                                               m",
      "m      H  mm                                                                                            m",
      "ms  k eH  mm                                                                                             o m",
      "mffffffH  m                                                                                            mmm",
      "m      H  m                                                                                                mmm",
      "m      H  mm                                                                                           m",
      "m      H  mm                                                                                           m",
      "m      H                                                                                            m",
      "m a d* H      p                                                                                      m",
      "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"
      ],
      [
      "fffffffffffffffffffff",
      "m         H        m",
      "m         H        m",
      "m         H        m",
      "m         H   ---     m",
      "m         H        m",
      "mfffff   fH       fm",
      "m         H        m",
      "m                  m",
      "m         H        m",
      "m         H        m",
      "m         H        m",
      "m         H       om",
      "mwwww           fffm",
      "mfffffffff         m",
      "m         H        m",
      "m         H        m",
      "m         H        m",
      "m         H       pm",
      "ffffffffffffffffffff"
      ],
      [
      "ffffffffffffffffffffffffffffffffffffffffff",
      "m         H                              m",
      "m         H    ---                          m",
      "m         H                              m",
      "m         H                              m",
      "m         H                              m",
      "mfffff   fH                             fm",
      "m         H        m",
      "m                  m",
      "m         H        m",
      "m         H        m",
      "m         H        m",
      "m         H       om",
      "mwwww           fffm",
      "mfffffffff         m",
      "m         H        m",
      "m         H        m",
      "m         H        m",
      "m         H       pm",
      "ffffffffffffffffffff"
      ],
    
      [
        "ffffffffffffffffffffffffffffffffffffffffff",
        "m         H                              m",
        "m         H    ---                          m",
        "m         H                              m",
        "m         H                              m",
        "m         H                              m",
        "mfffff   fH                             fm",
        "m         H                      m",
        "m                  m",
        "m         H        m",
        "m         H        m",
        "m         H        m",
        "m         H       om",
        "mwwww           fffm",
        "mfffffffff         m",
        "m         H        m",
        "m         H        m",
        "m         H        m",
        "m         H       pm",
        "ffffffffffffffffffff"
        ],
      [
        "ffffffffffffffffffffffffffffffffffffffffff",
        "m         H                              m",
        "m         H    ---                          m",
        "m         H                              m",
        "m         H                              m",
        "m         H                              m",
        "mfffff   fH                             fm",
        "m         H                      m",
        "m                  m",
        "m         H        m",
        "m         H        m",
        "m         H        m",
        "m         H       om",
        "mwwww           fffm",
        "mfffffffff         m",
        "m         H        m",
        "m         H        m",
        "m         H        m",
        "m         H       pm",
        "ffffffffffffffffffff"
        ],
        [
        "ffffffffffffffffffffffffffffffffffffffffff",
        "m         H                              m",
        "m         H    ---                          m",
        "m         H                              m",
        "m         H                              m",
        "m         H                              m",
        "mfffff   fH                             fm",
        "m         H                      m",
        "m                  m",
        "m         H        m",
        "m         H        m",
        "m         H        m",
        "m         H       om",
        "mwwww           fffm",
        "mfffffffff         m",
        "m         H        m",
        "m         H        m",
        "m         H        m",
        "m         H       pm",
        "ffffffffffffffffffff"
        ],
      
    ]


export default maps